CCS2/Models/Bill.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CCS2.Models
{
    public class Bill
    {
        public Bill() { Date = DateTime.Now; }

        public int BillId { get; set; }
        public int UserId { get; set; }
        public DateTime Date { get; set; }
        public string FileName { get; set; }
        public string FileExtension { get; set; }
        public byte[] FileContent { get; set; }
    }
}

CCS2/Models/Request.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace CCS2.Models
{
    public class Request
    {
        public Request()
        {
            DateRequested = DateTime.Now;
            CompleteDate = DateTime.Now.AddMonths(3);
            Approved = null;
        }

        [Key]
        public int RequestId { get; set; }
        public int ServiceId { get; set; }
        public int ClientId { get; set; }
        public DateTime DateRequested { get; set; }
        public string Description { get; set; }
        public bool? Approved { get; set; }
        public DateTime CompleteDate { get; set; }
    }
}

CCS2/Controllers/AdminController.cs
using CCS2.Models;
using CCS2.ViewModels;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CCS2.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class AdminController : Controller
    {
        private CcsContext _db = new CcsContext();

        //
        // GET: /Admin/

        public ActionResult Index()
        {
            return View();
        }

        //
        // GET: /Admin/Requests

        [HttpGet]
        public ActionResult Requests() 
        {
            // Get all the requests in the database
            string serviceName;
            string clientName;
            var reqs = _db.Requests;
            
            var Clients = _db.Clients.ToList();

            var Services = _db.Services.ToList();

            List<RequestVM> vreqs = new List<RequestVM>();
            foreach (var req in reqs)
            {
                clientName = _db.Clients.Find(req.ClientId).UserName;
                serviceName = _db.Services.Find(req.ServiceId).Name;
                vreqs.Add(new RequestVM() {
                    ClientName = clientName,
                    ServiceName = serviceName,
                    DateReq = req.DateRequested,
                    RequestId = req.RequestId,
                    Approved = false,
                    Description = req.Description,
                    DateComp = req.CompleteDate
                });
            }

            return View(vreqs);
        }

        //
        // GET: /Admin/RequestFor/id

        [HttpGet]
        public ActionResult RequestFor(int reqId)
        {
            var req = _db.Requests.FirstOrDefault(r => r.RequestId == reqId);

            RequestVM vreq = new RequestVM() { 
                RequestId = reqId,
                ClientName = _db.Clients.Find(req.ClientId).UserName,
                ServiceName = _db.Services.Find(req.ServiceId).Name,
                DateReq = req.DateRequested,
                DateComp = req.CompleteDate,
                Description = req.Description,
            };

            // Get all the reports for this request
            ViewBag.Reports = _db.Reports.Where(r => r.RequestId == req.RequestId);

            return View(vreq);
        }

        //
        // GET: /Admin/MakeReport/reqId

        [HttpGet]
        public ActionResult MakeReport(int reqId)
        {
            ViewBag.reqId = reqId;

            return View();
        }

        //
        // POST: /Admin/MakeReport/reqId

        [HttpPost]
        public ActionResult MakeReport(ProgressReport progRep, int reqId)
        {
            try
            {
                progRep.RequestId = reqId;
                if (progRep.Name == null || progRep.Name == "")
                    progRep.Name = "Report ID " + progRep.ProgressReportId.ToString();
                if (ModelState.IsValid)
                {
                    _db.Reports.Add(progRep);
                    _db.SaveChanges();

                    var req = _db.Requests.FirstOrDefault(r => progRep.RequestId == r.RequestId);

                    return RedirectToAction("RequestFor", new { reqId = req.RequestId });
                }
                else
                {
                    return View();
                }
            }
            catch
            {
                return View();
            }
        }

        public List<SelectListItem> GetAllUsers()
        {
            var allUsers = _db.Clients;

            List<SelectListItem> users = new List<SelectListItem>();

            int counter = -1;
            users.Add(new SelectListItem { Text = "All Users", Value = counter.ToString() });
            foreach (var user in allUsers)
            {
                counter++;
                users.Add(new SelectListItem { Text = user.UserName, Value = counter.ToString() });
            }

            return users;
        }

        //
        // GET: /Admin/SendMessage

        [HttpGet]
        public ActionResult SendMessage()
        {
            ViewBag.Users = GetAllUsers();

            return View();
        }

        //
        // POST: /Admin/SendMessage/Users

        [HttpPost]
        public ActionResult SendMessage(Message mes, string Users)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (Users != null && Users != "")
                    {
                        mes.SentTo = Int32.Parse(Users.ToString());
                    }

                    _db.Messages.Add(mes);
                    _db.SaveChanges();


                    //Email email = new Email();
                    //var user = _db.Clients.Find(mes.SentTo);
                    //if(email.SendEmail(mes.cMessage, user.Email, user.UserName, mes.Subject))
                        
                    return RedirectToAction("Messages", "Client", null);
                    
                }
                else
                {
                    return View();
                }
            }
            catch { return View(); }
        }

        //
        // GET: /Admin/Approve/reqId

        [HttpGet]
        public ActionResult Approve(int reqId)
        {
            var req = _db.Requests.Find(reqId);

            try
            {
                req.Approved = true;
                _db.SaveChanges();

                return RedirectToAction("Requests");
            }
            catch {
                return RedirectToAction("Requests");
            }
        }

        //
        // GET: /Admin/Deny/reqId

        [HttpGet]
        public ActionResult Deny(int reqId)
        {
            var req = _db.Requests.Find(reqId);

            try
            {
                req.Approved = false;
                _db.SaveChanges();

                return RedirectToAction("Requests");
            }
            catch
            {
                return RedirectToAction("Requests");
            }
        }

        //
        // GET: /Admin/AddNote
        [HttpGet]
        public ActionResult AddNote()
        {
            ViewBag.Users = GetAllUsers();

            return View();
        }

        //
        //  POST: /Admin/AddNote
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult AddNote(Note note, string Users)
        {
            if (Users != null && Users != "")
            {
                // The plus 1 is because the drop down starts at
                // 0 and the users list starts at 1
                note.UserId = Int32.Parse(Users) + 1;
            }
            note.Text = HttpUtility.HtmlEncode(note.Text);
            if (ModelState.IsValid)
            {
                _db.Notes.Add(note);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(note);
        }

        [HttpGet]
        public ActionResult Upload()
        {
            ViewBag.Users = GetAllUsers();
            return View();
        }

        [HttpPost]
        public ActionResult Upload(Bill file, HttpPostedFileBase fileUpload, string Users)
        {
            foreach (string upload in Request.Files)
            {
                file.FileExtension = fileUpload.ContentType;
                file.FileName = fileUpload.FileName;
                file.UserId = Int32.Parse(Users) + 1;

                int fileLength = fileUpload.ContentLength;
                Stream s = fileUpload.InputStream;

                file.FileContent = new byte[fileLength];

                s.Read(file.FileContent, 0, fileLength);
            }

            if (ModelState.IsValid)
            {
                _db.Bills.Add(file);
                _db.SaveChanges();
            }

            return RedirectToAction("Bills");
        }

        public FileContentResult Download(int id)
        {
            Bill file = _db.Bills.Find(id);

            return new FileContentResult(file.FileContent.ToArray(), file.FileExtension);
        }

        public ActionResult Bills()
        {
            List<Bill> bills = _db.Bills.ToList();

            return View(bills);
        }
    }
}

CCS2/Controllers/MessageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CCS2.Models;

namespace CCS2.Controllers
{
    [Authorize]
    public class MessageController : Controller
    {
        CcsContext _db = new CcsContext();
        //
        // GET: /Message/

        public ActionResult Index()
        {
            // Get the logged in user
            var username = User.Identity.Name;
            var user = _db.Clients.FirstOrDefault(u => u.UserName == username);
            // -1 seems to mean my keys aren't lining up, I will work on this
            var messages = _db.Messages.Where(m => m.ClientId == user.UserProfileId 
                || m.SentTo == user.UserProfileId - 1 || m.SentTo == -1);

            // get rid of deleted messages
            if (User.IsInRole("Administrator"))
                messages = messages.Where(m => m.AdminDelete == false);
            else
                messages = messages.Where(m => m.UserDelete == false);
            return View(messages);
        }

        //
        // GET: /Admin/Message/id
        [HttpGet]
        public ActionResult Message(int id)
        {
                        // Get the logged in user
            var username = User.Identity.Name;
            var user = _db.Clients.FirstOrDefault(u => u.UserName == username);
            
            // Get the message we are looking for
            var msg = _db.Messages.FirstOrDefault(m => m.MessageId == id);

            // Was the user sent you, everyone, or from you?
            if(msg.SentTo == (user.UserProfileId - 1) || msg.SentTo == -1 || msg.ClientId == user.UserProfileId)
                return View(msg);

            // No, then you can't see it
            return RedirectToAction("Index");
        }

        //
        // GET: /Message/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Message/Create

        [HttpPost]
        public ActionResult Create(FormCollection collection, Message msg)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    // Get the current user
                    string username = User.Identity.Name;
                    UserProfile user = _db.Clients.FirstOrDefault(u => u.UserName == username);

                    if(msg.Email == "" || msg.Email == null)
                    {
                        // If no email user is provide use the default
                        msg.Email = user.Email;
                    }

                    if (user.UserProfileId != 0)
                        msg.SentTo = 0;

                    msg.ClientId = user.UserProfileId;
                    _db.Messages.Add(msg);
                    _db.SaveChanges();
                    return RedirectToAction("Index");
                }
                else
                { return View(msg); }
            }
            catch
            {
                return View(msg);
            }
        }

        //
        // GET: /Message/Delete/5

        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /Message/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                Message mes = _db.Messages.Find(id);
                if (User.IsInRole("Administrator"))
                    mes.AdminDelete = true;
                else
                    mes.UserDelete = true;

                _db.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

CCS2/Views/Admin/AddNote.cshtml
@model CCS2.Models.Note

@{
    ViewBag.Title = "AddNote";
}

<h2>AddNote</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Note</legend>

        <div class="editor-label">
            @Html.Label("Select A User")
        </div>
        <div class="editor-field">
            @Html.DropDownList("Users")
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Text)
        </div>
        <div class="editor-field">
            @Html.TextAreaFor(model => model.Text, new { id = "htmlText" })
            @Html.ValidationMessageFor(model => model.Text)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>


<script type="text/javascript">
    // Found on stack overflow, changed /t to "   "
    $(document).delegate('#htmlText', 'keydown', function (e) {
        var keycode = e.keycode || e.which;

        if (keycode == 9) {
            e.preventDefault();
            var start = $(this).get(0).selectionStart;
            var end = $(this).get(0).selectionEnd;

            // set textarea value to: text before caret + tab + text after caret
            $(this).val($(this).val().substring(0, start) + "    " + $(this).val().substring(end));

            // put caret at right position again
            $(this).get(0).sectionStart = $(this).get(0).sectionEnd = start + 1;
        }
    });
</script>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CCS2/Views/Admin/Bad.cshtml
@{
    ViewBag.Title = "Bad";
}

<h2>Bad</h2>

<p>Oh no something has gone horribly wrong!</p>

CCS2/Views/Admin/Bills.cshtml
@model IEnumerable<CCS2.Models.Bill>

@{
    ViewBag.Title = "Invoices";
}

<h2>List of Invoices</h2>

<p>
    @Html.ActionLink("Add A bill", "Upload")
</p>
<table>
    <tr>
        <td>
            Date
        </td>
        <th>
            @Html.DisplayNameFor(model => model.FileName)
        </th>
        <th>
            Download
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Date)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FileName)
        </td>
        <td>
            @Html.ActionLink("Download", "Download", new { id = item.BillId })
        </td>
    </tr>
}

</table>

CCS2/Views/Admin/Index.cshtml
@{
    ViewBag.Title = "Administration Home";
}

<h2>Adminstration Home Page</h2>

<div class="admin_options">
    <div class="admin_link">
        @Html.ActionLink("View Project Requests", "Requests")
    </div>
    <br />
    <div class="admin_link">
        @Html.ActionLink("View Messages", "Index", "Message", null, null)
    </div>
    <br />
    <div class="admin_link">
        @Html.ActionLink("Send Message", "SendMessage")
    </div>
    <br />
    <div class="admin_link">
        @Html.ActionLink("Make Note", "AddNote")
    </div>
    <br />
    <div class="admin_link">
        @Html.ActionLink("View Invoices", "Bills")
    </div>
    <br />
    <div class="admin_link">
        @Html.ActionLink("Add Invoice", "Upload")
    </div>
</div>

CCS2/Views/Admin/MakeReport.cshtml
@model CCS2.Models.ProgressReport

@{
    ViewBag.Title = "Submit New Report";
}

<h2>Submit New Report</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>ProgressReport</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Notes)
        </div>
        <div class="editor-field">
            @Html.TextAreaFor(model => model.Notes)
            @Html.ValidationMessageFor(model => model.Notes)
        </div>

        <p>
            <input type="submit" value="Submit" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to Requests", "Requests")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CCS2/Views/Admin/RequestFor.cshtml
@model CCS2.ViewModels.RequestView
<link href="~/Content/Report.css" rel="stylesheet" />
<link href="~/Content/Details.css" rel="stylesheet" />
@{
    ViewBag.Title = "Request";
}

<fieldset>
    <legend>Project Request</legend>

    <div class="DetailHeader">
        <div class="DetailLeftCol">
            <div class="display-label, DetailLabel">
                 Client Name
            </div>
            <div class="display-field">
                @Html.DisplayFor(model => model.ClientName)
            </div>
            <div class="display-label, DetailLabel">
                    Service Name
            </div>
            <div class="display-field">
                @Html.DisplayFor(model => model.ServiceName)
            </div>
        </div>
        
        <div class="DetailRightCol">
            <div class="display-label, DetailLabel">
                 Date Requested
            </div>
            <div class="display-field">
                @Html.DisplayFor(model => model.DateReq)
            </div>

            <div class="display-label, DetailLabel">
                 To Be Completed By
            </div>
            <div class="display-field">
                @Html.DisplayFor(model => model.DateComp)
            </div>
        </div>
    </div>

    <div style="margin-top:25px;">
        <div class="display-label, DetailLabel">
             @Html.DisplayNameFor(model => model.Description)
        </div>
        <div class="display-field, DetailContent">
            @Html.DisplayFor(model => model.Description)
        </div>
    </div>
    
</fieldset>
<p>
    @Html.ActionLink("Back to List", "Index")
</p>

<h3>Progress Reports</h3>
<table>
    <tr>
        <th>
            Title
        </th>
        <th>
            Date
        </th>
    </tr>
    @foreach (var report in ViewBag.Reports)
    {
        <tr>
            <td>
                @report.Name
            </td>
            <td>
                @report.ReportDate
            </td>
            <td>
                @Html.ActionLink("Notes", "Report", "Client", new { id = report.ProgressReportId }, null)
            </td>
        </tr>
    }
</table>
<p>
    @Html.ActionLink("Add Report", "MakeReport", new { reqId = Model.RequestId })    
</p>

CCS2/Views/Admin/Requests.cshtml
@model IEnumerable<CCS2.ViewModels.RequestView>

@{
    ViewBag.Title = "Requests";
}

<h2>Client Requests</h2>

<table>
    <tr>
        <th>
            @Html.DisplayName("Sevrice Type")
        </th>
        <th>
            @Html.DisplayName("Client Name")
        </th>
        <th>
            @Html.DisplayName("Date Recieved")
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayName("Requested Completion Date")
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ServiceName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ClientName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateReq)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateComp)
        </td>
        <td>
            @Html.ActionLink("View", "RequestFor", new { reqId = item.RequestId })
        </td>
        <td>
            @Html.ActionLink("Approve", "Approve", new { reqId = item.RequestId }) | 
            @Html.ActionLink("Deny", "Deny", new { reqId = item.RequestId })
        </td>
    </tr>
}

</table>

CCS2/Views/Admin/SendMessage.cshtml
@model CCS2.Models.Message

@{
    ViewBag.Title = "Send Message";
}

<h2>Send Message</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Message</legend>

        <div class="editor-label">
            Send Message To
        </div>
        <div class="editor-field">
            @Html.DropDownList("Users")
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.Subject)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Subject)
            @Html.ValidationMessageFor(model => model.Subject)
        </div>

        <div class="editor-label">
            Message
        </div>
        <div class="editor-field">
            @Html.TextAreaFor(model => model.cMessage)
            @Html.ValidationMessageFor(model => model.cMessage)
        </div>

        <p>
            <input type="submit" value="Send" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CCS2/Views/Admin/Upload.cshtml
@model CCS2.Models.Bill

@{
    ViewBag.Title = "Upload Bill";
}

<h2>Create</h2>

@using (Html.BeginForm("Upload", "Admin", FormMethod.Post, new { enctype="multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Upload a Bill</legend>

        <div>
            @Html.DropDownList("Users")
        </div>
        <div class="editor-label">
            Upload a file
        </div>
        <div>
            <input type="file" name="fileUpload" />
        </div>

        <p>
            <input type="submit" value="Upload" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}